server:
  port: 8010
  server:
    error:
      include-message=always:
spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300
  application:
    name: insurance-service
#  main:
#    web-application-type: reactive
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"