server:
  port: 8084
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/customer_insurance_db}
  application:
    name: purchase-insurance-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka
