server:
  port: 8025
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/insurifyd}
  application:
    name: payment-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka
