server:
  port: 8098
spring:
  datasource:
    username: root
    password: root@123
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: authentication-service

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 692492348685-qpv81o821qgrrobknsffo375288t4hea.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
            redirectUri: http://localhost:8098/oauth2/authorization/google