server:
  port: 8080
spring:
  datasource:
    username: root

<<<<<<< HEAD
    password: password@123
=======
    password: root
>>>>>>> 0766884b8fe1faab9226e4dc67909f073f4fd0f6

    url: jdbc:mysql://localhost:3306/insurifyDb

    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: authentication-service

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 692492348685-qpv81o821qgrrobknsffo375288t4hea.apps.googleusercontent.com
            clientSecret: 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



