server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurifydb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: password@123
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: authentication-service

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 692492348685-657c7e1c0t3t05k2ch9kp5gd08mbloj3.apps.googleusercontent.com
#            clientSecret: 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
#            scope:
#              - email
#              - profile